import { Analytics } from '@/components/Analytics';
import Header from '@/components/Header';
import { Raleway, Bitter } from '@next/font/google';
import './globals.css';

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway',
});
const bitter = Bitter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`bg-zinc-800 text-zinc-100 antialiased ${bitter.className} ${raleway.variable}`}
    >
      <head>
        <title>Find A Table</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className='min-h-screen'>
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
